kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-consul-pv1
  labels:
    type: local
  namespace: istio-system
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  hostPath:
    path: /srv/data-consul-pv1
    type: DirectoryOrCreate
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-jaeger
  namespace: istio-system
spec:
  version: 7.5.2
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lzy-k8s-1.cluster.peidan.me
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
        storageClassName: hostpath
