apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  name: ts-mongo-monitoring
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-jaeger
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 30.0.1
    chart: kube-prometheus-stack-30.0.1
    heritage: Helm
    release: kube-prometheus-stack
spec:
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_app
      targetLabel: instance
  namespaceSelector:
    matchNames:
    - tt
  selector:
    matchLabels:
      FDG-node-type: mongo
