kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: tt
  name: account-tt-manager-mysvh

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tt
  name: role-tt-manager-mysvh
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-tt-manager-mysvh
  namespace: tt
subjects:
- kind: ServiceAccount
  name: account-tt-manager-mysvh
  namespace: tt
roleRef:
  kind: Role
  name: role-tt-manager-mysvh
  apiGroup: rbac.authorization.k8s.io