{
 "title": "Home",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "#Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(jaeger_spans_saved_by_svc_total[1m]))  by (svc)",
     "legendFormat": "{{sec}}"
    },
    {
     "expr": "sum(increase(jaeger_spans_saved_by_svc_total{svc='ts-ui-dashboard.tt'}[1m]))  by (svc)",
     "legendFormat": "Overall Traces"
    }
   ]
  },
  {
   "title": "Trace Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "startTimeMillis", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "duration", "id": "1", "type": "avg" }
     ],
     "query": "process.serviceName: ts-ui-dashboard.tt",
     "timeField": "startTimeMillis"
    },
    {
     "bucketAggs": [
      { "field": "startTimeMillis", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "duration",
       "id": "1",
       "settings": {
        "percents": [
         "99",
         " 90"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "process.serviceName: ts-ui-dashboard.tt",
     "timeField": "startTimeMillis"
    }
   ]
  },
  { "title": "Machine Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "non-ilde",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "non-ilde",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Relative CPU Usage",
   "type": "timeseries",
   "description": "non-ilde",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) / sum by (instance)(rate(node_cpu_seconds_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Relative Memory Usage",
   "type": "timeseries",
   "description": "non-ilde",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Recv Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"cni0\"}[1m])*8",
     "legendFormat": "{{instance}}-{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens18\"}[1m])*8",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Network Trans Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"cni0\"}[1m])*8",
     "legendFormat": "{{instance}}-{{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens18\"}[1m])*8",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "description": "non-ilde",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"tt\"}[1m]) * 100) by (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "description": "non-ilde",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"tt\", container=~\"ts.*\", service=\"kubelet\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Recv Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"tt\", container=~\".*\", service=\"kubelet\"}[1m]) * 8) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Trans Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"tt\", container=~\".*\", service=\"kubelet\"}[1m]) * 8) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}