apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: tt
  name: http-fault-test
spec:
  hosts:
  - ts-verification-code-service
  http:
  - fault:
      delay:
        fixedDelay: 3s
        percentage:
          value: 100
    route:
    - destination:
        host: ts-verification-code-service